# Generated by Django 3.0.8 on 2020-09-03 22:51
import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ('id', 'username')},
        ),
        migrations.AddField(
            model_name='usuario',
            name='birth_date',
            field=models.DateField(default=datetime.date(2020, 7, 24), verbose_name='Data de nascimento'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(default=4564, max_length=11, unique=True, verbose_name='CPF'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='fullname',
            field=models.CharField(max_length=1000, null=True, verbose_name='Nome completo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rg',
            field=models.CharField(default=12354, max_length=7, unique=True, verbose_name='RG'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='Número do título de eleitor'),
        ),
    ]
