# Generated by Django 3.0.8 on 2020-09-03 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_remove_usuario_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='fullname',
        ),
    ]
