# Generated by Django 3.0.8 on 2020-09-03 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_auto_20200903_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fullname',
            field=models.CharField(max_length=1000, null=True, verbose_name='Nome completo'),
        ),
    ]
