# Generated by Django 3.0.8 on 2020-09-03 23:05
import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_auto_20200903_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='birth_date',
            field=models.DateField(default=datetime.date(2020, 7, 24), verbose_name='Data de nascimento'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cpf',
            field=models.IntegerField(default='', verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rg',
            field=models.IntegerField(default='', verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.IntegerField(unique=True, verbose_name='Número do título de eleitor'),
        ),
    ]
