# Generated by Django 3.0.8 on 2020-09-03 23:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0013_usuario_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='birth_date',
            field=models.DateField(default=datetime.date(2020, 7, 24), verbose_name='Data de nascimento'),
        ),
    ]
