# Generated by Django 3.0.8 on 2020-09-03 23:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0014_auto_20200903_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='birth_date',
            field=models.DateField(default=datetime.date(2020, 9, 3), verbose_name='Data de nascimento'),
        ),
    ]
