# Generated by Django 3.1 on 2020-09-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0016_remove_usuario_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='user_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
