# Generated by Django 3.1.1 on 2020-09-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0020_auto_20200927_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='name',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(max_length=14, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fullname',
            field=models.CharField(max_length=1000, verbose_name='Nome completo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rg',
            field=models.CharField(default=2, max_length=10, verbose_name='RG'),
            preserve_default=False,
        ),
    ]
