# Generated by Django 3.1.1 on 2020-09-27 23:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0002_auto_20200927_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='EleicaoEstadual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('PR', 'Governadores'), ('SN', 'Deputados estaduais')], default=1, max_length=2)),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default=1, max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='eleicaofederal',
            name='estado',
        ),
        migrations.AlterField(
            model_name='eleicaofederal',
            name='tipo',
            field=models.CharField(choices=[('PR', 'Presidentes'), ('SN', 'Senadores'), ('DF', 'Deputados Federais')], default=1, max_length=2),
        ),
    ]
