# Generated by Django 3.1.1 on 2020-09-27 23:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0003_auto_20200927_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dat_ini', models.DateField(default=django.utils.timezone.now, verbose_name='Data inicío')),
                ('dat_fim', models.DateField(default=django.utils.timezone.now, verbose_name='Data fim')),
            ],
        ),
        migrations.AlterField(
            model_name='eleicaofederal',
            name='data',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='eleicaofederal',
            name='tipo',
            field=models.CharField(choices=[('PR', 'Presidentes'), ('SN', 'Senadores'), ('DF', 'Deputados Federais')], default=1, max_length=2, verbose_name='Tipo'),
        ),
    ]
