# Generated by Django 3.1.1 on 2020-09-28 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0006_auto_20200927_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleicaoestadual',
            name='ano',
            field=models.IntegerField(choices=[(2018, 2018), (2019, 2019), (2020, 2020)], default=2020, verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='eleicaofederal',
            name='ano',
            field=models.IntegerField(choices=[(2018, 2018), (2019, 2019), (2020, 2020)], default=2020, verbose_name='Ano'),
        ),
    ]
