# Generated by Django 3.1.1 on 2020-09-28 01:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0009_auto_20200927_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(default=2020, verbose_name='Ano')),
                ('tipo', models.CharField(choices=[('Eleição Federal', (('PR', 'Presidentes'), ('SN', 'Senadores'), ('DF', 'Deputados Federais'))), ('Eleição Estadual', (('PR', 'Governadores'), ('SN', 'Deputados estaduais')))], default=1, max_length=2, verbose_name='Tipo')),
                ('estado', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, null=True)),
            ],
            options={
                'verbose_name': 'Eleição federal',
                'verbose_name_plural': 'Eleições federais',
                'ordering': ('ano', 'tipo'),
            },
        ),
        migrations.DeleteModel(
            name='EleicaoEstadual',
        ),
        migrations.DeleteModel(
            name='EleicaoFederal',
        ),
        migrations.AlterModelOptions(
            name='candidato',
            options={'ordering': ('nome', 'nascimento'), 'verbose_name': 'Candidato', 'verbose_name_plural': 'Candidatos'},
        ),
        migrations.AddField(
            model_name='candidato',
            name='estado',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default=1, max_length=2, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='foto',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='perfil/', verbose_name='Foto de perfil'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='nascimento',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de nascimento'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='nome',
            field=models.CharField(default=1, max_length=255, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidato',
            name='titulo',
            field=models.CharField(choices=[('PR', 'Presidente'), ('SN', 'Senador'), ('VR', 'Vereador')], default=1, max_length=2, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='turno',
            name='turno',
            field=models.IntegerField(default='1', verbose_name='Turno'),
        ),
        migrations.AddField(
            model_name='turno',
            name='eleicao',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='votacao.eleicao'),
            preserve_default=False,
        ),
    ]
