# Generated by Django 3.0.8 on 2020-09-28 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0012_auto_20200928_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidato',
            options={'ordering': ('id', 'nome', 'nascimento'), 'verbose_name': 'Candidato', 'verbose_name_plural': 'Candidatos'},
        ),
        migrations.AlterModelOptions(
            name='eleicao',
            options={'ordering': ('id', 'ano', 'tipo'), 'verbose_name': 'Eleição', 'verbose_name_plural': 'Eleições'},
        ),
        migrations.AlterModelOptions(
            name='turno',
            options={'ordering': ('id', 'dat_ini', 'dat_fim'), 'verbose_name': 'Turno', 'verbose_name_plural': 'Turnos'},
        ),
        migrations.CreateModel(
            name='VotacaoTurnoCandidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votos', models.IntegerField()),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacao.Candidato')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacao.Turno')),
            ],
            options={
                'verbose_name': 'Votações por turno por candidato',
                'verbose_name_plural': 'Turnos',
                'ordering': ('id', 'turno', 'candidato'),
            },
        ),
    ]
