# Generated by Django 3.0.8 on 2020-09-28 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0013_auto_20200928_1249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turno',
            options={},
        ),
    ]
