# Generated by Django 3.0.8 on 2020-09-28 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0014_auto_20200928_1258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votacaoturnocandidato',
            options={'ordering': ('id', 'turno', 'candidato'), 'verbose_name': 'Votação por turno por candidato', 'verbose_name_plural': 'Votações por turno por candidato'},
        ),
    ]
