# Generated by Django 3.1.1 on 2020-09-28 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0021_auto_20200928_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrovotacao',
            name='eleicao',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='votacao.eleicao'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrovotacao',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacao.turno'),
        ),
    ]
