# Generated by Django 3.0.8 on 2020-09-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0022_auto_20200928_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrovotacao',
            name='usuario',
            field=models.IntegerField(),
        ),
    ]
